version: '3'

services:
    ###> doctrine/doctrine-bundle ###
    database:
        environment:
            POSTGRES_DB: symfony-project
            POSTGRES_PASSWORD: ChangeMe
            POSTGRES_USER: webapp
        ports:
            - "5432:5432"
    ###< doctrine/doctrine-bundle ###
    web:
        container_name: server
        build: .
        ports:
            - 8080:80
