---
host_server_name: "symfony-project.it"
project_versions_root: "/var/www/symfony-project"
project_root_dir: "{{ project_versions_root }}/current"
project_var_dir: "{{ project_root_dir }}/var"
project_console_path: "{{ project_root_dir }}/bin/console"
apache_web_dir: "{{ project_root_dir }}/public"

postgresql_databases:
    - name: symfony-project
postgresql_users:
    - name: app
      password: "{{ vault_database_password }}"
postgres_users_no_log: true
postgresql_hba_entries:
    - {type: local, database: all, user: postgres, auth_method: peer}
    - {type: local, database: all, user: all, auth_method: md5}
    - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}"}
    - {type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}"}

apache_vhosts:
    # Additional properties:
    # 'serveradmin, serveralias, allow_override, options, extra_parameters'.
    - servername: "{{ host_server_name }}"
      documentroot: "{{ apache_web_dir }}"
      extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ apache_web_dir }}"

php_version: '8.0'
php_default_version_debian: "{{ php_version }}"
php_packages:
    - php{{ php_version }}-fpm
    - php{{ php_version }}-xml
    - php{{ php_version }}-opcache
    - php{{ php_version }}-apcu
    - php{{ php_version }}-mbstring
php_pgsql_package: php{{ php_version }}-pgsql
php_enable_php_fpm: true
php_date_timezone: "Europe/Rome"

nodejs_version: "17.x"
